import Head from "next/head";
import styles from "../styles/Home.module.css";
import { PrismaClient } from "@prisma/client";
import Grid from "../components/grid";

export async function getServerSideProps() {
  const prisma = new PrismaClient();
  const homes = await prisma.home.findMany();
  return {
    props: {
      homes: JSON.parse(JSON.stringify(homes)),
    },
  };
}

export default function Home(props) {
  var homes = props.homes;
  return (
    <>
      <Head>
        <title>Voila</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className={styles.heading}>Top-rated places to stay</h1>
      <p className={styles.explore}>
        Explore some of the best places in the world
      </p>
      <Grid homes={homes} />
    </>
  );
}
